### ISSUE TITLE
Cypher exporter / shell's dump command improvements

### ISSUE THREAD

**Issue by jotomo** [neo4j/neo4j#2625]
This issue ties together all bugs related to the shell's dump command.

## Schema support

- [ ] Constraints using indexes during import: there needs a way to wait for indexes to become available after creating them, otherwise the import takes forever.
  - [ ] The shell could be extended with a command to achieve the above, but this functionality might be better introduced in Cypher, some discussion occurred here: https://github.com/neo4j/neo4j/issues/2491#issuecomment-44791266. Edit: there actually already is the _schema await_ command which can be used for that purpose.
- [x] Currently indexes and schema creation statements aren't properly generated, they need to be separate statements. Issue: https://github.com/neo4j/neo4j/issues/2491
  - [x] @nawroth raised the question whether this change will break the integrated live console in the manual here: https://github.com/neo4j/neo4j/pull/2576#issuecomment-46100875 So this needs to be tested.

## Robustness

- [ ] Newline characters need to be properly escaped (also: tab, ...). Issue: https://github.com/neo4j/neo4j/issues/2577
- [ ] Strings containing _&&_ confuse the shell. There might be more problems if the shell attempts to parse something inside a string. Issue: https://github.com/neo4j/neo4j/issues/2579
- [ ] Byte arrays are exported as int arrays. Does Cypher support byte arrays? Should it? Issue: https://github.com/neo4j/neo4j/issues/2491
- [ ] Maybe (no personal experience with large data sets): scaling to allow inserting more data than fitting a single transaction. This depends on what the goal of the _dump_ command is, whether it shall be usable the same way SQL people dump DBs to SQL scripts to load them into another DB or whether dump is designed for smaller data sets (this should also be documented, so people will know what to expect from the command).
- [ ] Cosmetics: there shouldn't be a BEGIN/COMMIT pair for schema creation if no schema is created
- [x] Order of dumped statements (esp. index/constrains), discussion: https://github.com/neo4j/neo4j/issues/4437

**Comment by jexp** [comment]
@jotomo Some comments:
- The newline and && issue is obviously still open.
- This implementation of dump was not meant for large imports (long story), if you need something like that look at: https://github.com/jexp/neo4j-shell-tools#cypher-export (happy to fix any issues there).
- cypher does not know byte arrays, so it can only import them back as int-arrays, this will be better with other transports like Bolt 
- even with parameters, there is no good way of expressing a byte array in JSON (besides base64 encoded string)
- schema await is a bit tricky as it is shell specific, we would have to break up the exporter into distinguished steps and have dump call them individually (which might make sense anyway)

**Comment by bryanph** [comment]
@jexp is this newline issue going to be resolved any time soon?
